name: Test GitHub Actions AWS OIDC

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show GitHub OIDC information
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Repository ID: $(gh api repos/$GITHUB_REPOSITORY --jq '.id')"
          echo "Repository Owner ID: $(gh api users/$GITHUB_REPOSITORY_OWNER --jq '.id')"
          echo "Ref: $GITHUB_REF"
